CREATE TABLE TS_PROD_CAT(
    ID SERIAL,
    NAME VARCHAR(200) NOT NULL,
    IS_SUB_CAT NUMERIC(1, 0) NOT NULL,
    PARENT_ID INT NOT NULL
);
CREATE UNIQUE INDEX PK_TS_PROD_CAT ON TS_PROD_CAT(ID);
ALTER TABLE TS_PROD_CAT
ADD CONSTRAINT PK_TS_PROD_CAT PRIMARY KEY USING INDEX PK_TS_PROD_CAT;