create table User_table(
	id int not null,
	name varchar(20) not null,
	user_type numeric(1, 0),
	created_date date,
	user_pass varchar(32)
);
create unique index pk_user_table on User_table (id, user_pass);
alter table User_table
add constraint pk_user_table primary key using index pk_user_table;
CREATE TABLE PRODUCT(
	PROD_ID INT NOT NULL,
	PROD_NAME VARCHAR(200) NOT NULL,
	PROD_PRICE NUMERIC(20, 2) NOT NULL,
	PROD_DATE DATE NOT NULL,
	PROD_DATETIME TIMESTAMP NOT NULL,
	IS_AVAILABLE BOOLEAN NOT NULL,
	USER_ID INT NOT NULL,
	CAT_ID INT NOT NULL,
	SUB_CAT_ID INT
);
CREATE TABLE PROD_CAT(
	ID INT NOT NULL,
	NAME VARCHAR(200) NOT NULL,
	IS_SUB_CAT NUMERIC(1, 0) NOT NULL,
	PARENT_ID INT NOT NULL
);
CREATE UNIQUE INDEX PK_PRODUCT ON PRODUCT(PROD_ID);
ALTER TABLE PRODUCT
ADD CONSTRAINT PK_PRODUCT PRIMARY KEY USING INDEX PK_PRODUCT;
CREATE INDEX FK_PRODUCT ON PRODUCT(USER_ID, CAT_ID, SUB_CAT_ID);
ALTER TABLE PRODUCT
ADD CONSTRAINT FK_PRODUCT FOREIGN KEY (USER_ID) REFERENCES USER_TABLE (ID);
ALTER TABLE PRODUCT
ADD CONSTRAINT FK_PRODUCT FOREIGN KEY (CAT_ID) REFERENCES PROD_CAT(ID);
ALTER TABLE PRODUCT
ADD CONSTRAINT FK_PRODUCT FOREIGN KEY (SUB_CAT_ID) REFERENCES PROD_CAT(ID);
CREATE TABLE USER_TYPE(
	ID NUMERIC(1, 0) NOT NULL,
	TYPE_NAME VARCHAR(20)
);
CREATE UNIQUE INDEX PK_USER_TYPE ON USER_TYPE(ID);
ALTER TABLE USER_TYPE
ADD CONSTRAINT PK_USER_TYPE PRIMARY KEY USING INDEX PK_USER_TYPE;
CREATE TABLE OPER_PRIV(
	ID INT NOT NULL,
	OPER_NAME VARCHAR(50),
	USER_ID NUMERIC(1, 0) NOT NULL
);
CREATE UNIQUE INDEX PK_OPER_PRIV ON OPER_PRIV (ID, OPER_NAME);
ALTER TABLE OPER_PRIV
ADD CONSTRAINT PK_OPER_PRIV PRIMARY KEY USING INDEX PK_OPER_PRIV;
CREATE INDEX FK_OPER_PRIV ON OPER_PRIV(USER_ID);
ALTER TABLE OPER_PRIV
ADD CONSTRAINT FK_OPER_PRIV FOREIGN KEY (USER_ID) REFERENCES USER_TYPE(ID);
CREATE TABLE PROD_SALES_HIST(HIST_ID INT NOT NULL, HIST_DATE DATE NOT NULL);
ALTER TABLE PROD_SALES_HIST
ADD HIST_DATETIME TIMESTAMP;
ALTER TABLE PROD_SALES_HIST
ADD USER_ID INT NOT NULL;
CREATE UNIQUE INDEX PK_PROD_SALES_HIST ON PROD_SALES_HIST(HIST_ID, HIST_DATE);
ALTER TABLE PROD_SALES_HIST
ADD CONSTRAINT PK_PROD_SALES_HIST PRIMARY KEY USING INDEX PK_PROD_SALES_HIST;
CREATE INDEX FK_PROD_SALES_HIST_USER ON PROD_SALES_HIST(USER_ID);
ALTER TABLE PROD_SALES_HIST
ADD CONSTRAINT FK_PROD_SALES_HIST_USER FOREIGN KEY (USER_ID) REFERENCES USER_TABLE (ID);
CREATE TABLE PROD_SALES_HIST_TKN(
	HIST_ID INT NOT NULL,
	ITEM_NO NUMERIC(23, 2) NOT NULL
);
ALTER TABLE PROD_SALES_HIST_TKN
ADD PROD_ID INT NOT NULL;
ALTER TABLE PROD_SALES_HIST_TKN
ADD FIRST_PRICE NUMERIC(20, 2);
ALTER TABLE PROD_SALES_HIST_TKN
ADD SOLD_PRICE NUMERIC(20, 2);
CREATE UNIQUE INDEX PK_PROD_SALES_HIST_TKN ON PROD_SALES_HIST_TKN(HIST_ID, ITEM_NO);
ALTER TABLE PROD_SALES_HIST_TKN
ADD CONSTRAINT PK_PROD_SALES_HIST_TKN PRIMARY KEY USING INDEX PK_PROD_SALES_HIST_TKN;
CREATE INDEX FK_PROD_SALES_HIST_TKN ON PROD_SALES_HIST_TKN(PROD_ID);
ALTER TABLE PROD_SALES_HIST_TKN
ADD CONSTRAINT FK_PROD_SALES_HIST_TKN FOREIGN KEY (PROD_ID) REFERENCES PRODUCT(PROD_ID);
CREATE TABLE PROD_PICTURE(
	PIC_ID INT NOT NULL,
	DESCRIPTION TEXT,
	PROD_URL VARCHAR(2000),
	PROD_ID INT NOT NULL
);
CREATE UNIQUE INDEX PK_PROD_PICTURE ON PROD_PICTURE(PIC_ID);
ALTER TABLE PROD_PICTURE
ADD CONSTRAINT PK_PROD_PICTURE PRIMARY KEY USING INDEX PK_PROD_PICTURE;
create table Report(
	id int not null,
	r_date date not null,
	r_text text,
	user_id int not null,
	prod_id int,
	user_reported_id int,
	report_datetime timestamp
);
create unique index pk_report on report (id, r_date);
alter table Report
add constraint pk_report primary key using index pk_report;
alter table Report
add constraint fk_report foreign key (user_id) references user_table (id);