CREATE TABLE PROD_SALES_HIST(HIST_ID INT NOT NULL,HIST_DATE DATE NOT NULL);
ALTER TABLE PROD_SALES_HIST ADD HIST_DATETIME TIMESTAMP;
ALTER TABLE PROD_SALES_HIST ADD USER_ID INT NOT NULL;

CREATE UNIQUE INDEX PK_PROD_SALES_HIST ON PROD_SALES_HIST(HIST_ID,HIST_DATE);
ALTER TABLE PROD_SALES_HIST ADD CONSTRAINT PK_PROD_SALES_HIST PRIMARY KEY USING INDEX PK_PROD_SALES_HIST;

CREATE INDEX FK_PROD_SALES_HIST_USER ON PROD_SALES_HIST(USER_ID);
ALTER TABLE PROD_SALES_HIST ADD CONSTRAINT FK_PROD_SALES_HIST_USER FOREIGN KEY (USER_ID) REFERENCES USER_TABLE (ID);
