CREATE TABLE OPER_PRIV(
    ID INT NOT NULL,
    OPER_NAME VARCHAR(50),
    USER_ID NUMERIC(1, 0) NOT NULL
);
CREATE UNIQUE INDEX PK_OPER_PRIV ON OPER_PRIV (ID, OPER_NAME);
ALTER TABLE OPER_PRIV
ADD CONSTRAINT PK_OPER_PRIV PRIMARY KEY USING INDEX PK_OPER_PRIV;
CREATE INDEX FK_OPER_PRIV ON OPER_PRIV(USER_ID);
ALTER TABLE OPER_PRIV
ADD CONSTRAINT FK_OPER_PRIV FOREIGN KEY (USER_ID) REFERENCES USER_TYPE(ID);