CREATE TABLE PROD_PICTURE(
    PIC_ID INT NOT NULL,
    DESCRIPTION TEXT,
    PROD_URL VARCHAR(2000),
    PROD_ID INT NOT NULL
);
CREATE UNIQUE INDEX PK_PROD_PICTURE ON PROD_PICTURE(PIC_ID);
ALTER TABLE PROD_PICTURE
ADD CONSTRAINT PK_PROD_PICTURE PRIMARY KEY USING INDEX PK_PROD_PICTURE;