CREATE TABLE PROD_CAT(
    ID INT NOT NULL,
    NAME VARCHAR(200) NOT NULL,
    IS_SUB_CAT NUMERIC(1, 0) NOT NULL,
    PARENT_ID INT NOT NULL
);
CREATE UNIQUE INDEX PK_PROD_CAT ON PROD_CAT(ID, NAME, IS_SUB_CAT);
ALTER TABLE PROD_CAT
ADD CONSTRAINT PK_PROD_CAT PRIMARY KEY USING PK_PROD_CAT;