CREATE TABLE TS_PROD_PICTURE(
    PIC_ID Serial,
    DESCRIPTION TEXT,
    PROD_URL VARCHAR(2000),
    PROD_ID INT NOT NULL
);
CREATE UNIQUE INDEX PK_TS_PROD_PICTURE ON TS_PROD_PICTURE(PIC_ID);
ALTER TABLE TS_PROD_PICTURE
ADD CONSTRAINT PK_TS_PROD_PICTURE PRIMARY KEY USING INDEX PK_TS_PROD_PICTURE;
CREATE INDEX FK_TS_PROD_PICTURE ON TS_PROD_PICTURE(PROD_ID);
ALTER TABLE TS_PROD_PICTURE
ADD CONSTRAINT FK_TS_PROD_PICTURE FOREIGN KEY (PROD_ID) REFERENCES TS_PRODUCT(PROD_ID);