CREATE TABLE PROD_SALES_HIST_TKN(
    HIST_ID INT NOT NULL,
    ITEM_NO NUMERIC(23, 2) NOT NULL
);
ALTER TABLE PROD_SALES_HIST_TKN
ADD PROD_ID INT NOT NULL;
ALTER TABLE PROD_SALES_HIST_TKN
ADD FIRST_PRICE NUMERIC(20, 2);
ALTER TABLE PROD_SALES_HIST_TKN
ADD SOLD_PRICE NUMERIC(20, 2);
CREATE UNIQUE INDEX PK_PROD_SALES_HIST_TKN ON PROD_SALES_HIST_TKN(HIST_ID, ITEM_NO);
ALTER TABLE PROD_SALES_HIST_TKN
ADD CONSTRAINT PK_PROD_SALES_HIST_TKN PRIMARY KEY USING INDEX PK_PROD_SALES_HIST_TKN;
CREATE INDEX FK_PROD_SALES_HIST_TKN ON PROD_SALES_HIST_TKN(PROD_ID);
ALTER TABLE PROD_SALES_HIST_TKN
ADD CONSTRAINT FK_PROD_SALES_HIST_TKN FOREIGN KEY (PROD_ID) REFERENCES PRODUCT(PROD_ID);