CREATE TABLE TS_PROD_SALES_HIST_TKN(
    HIST_ID INT NOT NULL,
    ITEM_NO NUMERIC(23, 2) NOT NULL
);
ALTER TABLE TS_PROD_SALES_HIST_TKN
ADD PROD_ID INT NOT NULL;
ALTER TABLE TS_PROD_SALES_HIST_TKN
ADD FIRST_PRICE NUMERIC(20, 2);
ALTER TABLE TS_PROD_SALES_HIST_TKN
ADD SOLD_PRICE NUMERIC(20, 2);
CREATE UNIQUE INDEX PK_TS_PROD_SALES_HIST_TKN ON TS_PROD_SALES_HIST_TKN(HIST_ID, ITEM_NO);
ALTER TABLE TS_PROD_SALES_HIST_TKN
ADD CONSTRAINT PK_TS_PROD_SALES_HIST_TKN PRIMARY KEY USING INDEX PK_TS_PROD_SALES_HIST_TKN;
CREATE INDEX FK_TS_PROD_SALES_HIST_TKN ON TS_PROD_SALES_HIST_TKN(PROD_ID);
ALTER TABLE TS_PROD_SALES_HIST_TKN
ADD CONSTRAINT FK_TS_PROD_SALES_HIST_TKN FOREIGN KEY (PROD_ID) REFERENCES TS_PRODUCT(PROD_ID);
CREATE INDEX FK_TS_PROD_SALES_HIST ON TS_PROD_SALES_HIST_TKN(HIST_ID);
ALTER TABLE TS_PROD_SALES_HIST_TKN
ADD CONSTRAINT FK_TS_PROD_SALES_HIST FOREIGN KEY (HIST_ID) REFERENCES TS_PROD_SALES_HIST(HIST_ID);