CREATE TABLE USER_TYPE(
    ID NUMERIC(1, 0) NOT NULL,
    TYPE_NAME VARCHAR(20)
);
CREATE UNIQUE INDEX PK_USER_TYPE ON USER_TYPE(ID);
ALTER TABLE USER_TYPE
ADD CONSTRAINT PK_USER_TYPE PRIMARY KEY USING INDEX PK_USER_TYPE;